baseurl = "/"
title   = "Michael C.C. Shih"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

googleAnalytics = "UA-163877741-1"
disqusShortname = "mikecshih"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Mike Shih's website"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
  
  [params.logo]
    logoText = "Michael C.C. Shih"
    logoHomeLink = "/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/eufmike"

  [[params.social]]
    name = "email"
    url  = "mailto:m.cc.shih@gmail.com"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/michaelcshih/"

[languages]
  [languages.en]
    title = "Michael C.C. Shih"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu] 
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "publications"
    name       = "Publications"
    url        = "publications/"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"